version: '3.9' #versão utilizada do yml
services:
  mongodb: #criar  o serviço com o nome que eu queira
    image: mongo:4.4.6 #subir a imagem e a sua versão
    container_name: meu-mongo
    networks:
      - compose-bridge #determinar a rede 

  alurabooks:
    image: aluradocker/alura-books:1.0 
    container_name: alurabooks
    networks:
      - compose-bridge
    ports: #quais portas deve executar no container e maquina
      - 3000:3000

    depends_on: #faz com que gere um dependência até o container estiver pronto
      - mongodb
networks:
  compose-bridge: #criação da rede que será comunicada
    driver: bridge

  

